site:
  title: Mario Malić
  start_page: portfolio::homepage.adoc
  url: https://mariomalic.com
  robots: |
    User-agent: *
    Allow: /
  keys:
    google_analytics: 'G-HBJ5T0G7MY'

content:
  sources:
  - url: https://gitlab.com/mario-malic/portfolio/component
    branches: main
ui:
  bundle:
    url: https://gitlab.com/mario-malic/portfolio/docs-site/-/jobs/artifacts/main/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  
output:
  clean: true
  dir: ../build

