site:
  title: Mario Malić
  start_page: portfolio::homepage.adoc
  url: https://mariomalic.com
  robots: allow
  keys:
    google_analytics: 'G-HBJ5T0G7MY'

content:
  sources:
  - url: https://github.com/MarioMalic/portfolio.git
    branches: main
ui:
  bundle:
    url: https://github.com/MarioMalic/website/releases/download/ui/modified-ui.zip
    snapshot: true
  
output:
  clean: true
  dir: ../build

